name: Build (Ubuntu)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:25.04

    steps:
      - name: Update system
        run: apt update

      - name: Install dependencies
        run: apt install -y
          cmake extra-cmake-modules kwin-dev libkf6config-dev
          libkf6configwidgets-dev libkf6coreaddons-dev libkf6kcmutils-dev
          libkf6windowsystem-dev qt6-base-dev libdrm-dev

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr

      - name: Build
        run: cmake --build build --parallel
